name: Generate Pack SHA-1 and Config

on:
  release:
    types: [published]

jobs:
  build-and-hash:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Resource Pack
        run: |
          zip -r BazaCraft.zip assets/ pack.mcmeta pack.png

      - name: Calculate SHA-1 and UUID
        id: pack_info
        run: |
          HASH=$(sha1sum BazaCraft.zip | awk '{print $1}')
          echo "pack_hash=$HASH" >> $GITHUB_OUTPUT
          PACK_UUID=$(uuidgen)
          echo "pack_uuid=$PACK_UUID" >> $GITHUB_OUTPUT

      - name: Update Release Description
        uses: softprops/action-gh-release@v2
        with:
          files: BazaCraft.zip
          body: |
            ### 📦 Конфиг для вашего server.properties
            Скопируйте этот блок текста полностью и вставьте в конфигурацию сервера:
            
            ```properties
            resource-pack=https://github.com github.repository /releases/download/{{ github.event.release.tag_name }}/BazaCraft.zip
            resource-pack-sha1=\${{ steps.pack_info.outputs.pack_hash }}
            resource-pack-id=\${{ steps.pack_info.outputs.pack_uuid }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
